### PR TITLE
Github action for docker runtime

### PR DESCRIPTION
**Pull request by Luke-Roy-IBM**

### CODE REVIEW

**Comment by Luke-Roy-IBM** [comment]
@dgrove-oss I create the GitHub action. The configuration in GitHub is still required as I don´t have the necessary permissions.

**Comment by dgrove-oss** [comment]
Hi @Luke-Roy-IBM.  Thanks for starting on this, but this repo is a bit of an oddball compared to the other runtimes. If you look in .travis.yml and then poke into tools/travis you'll see that the scripts here were pretty divergent from the other runtimes.  

Another general problem with this runtime is that the base image is based on python 3.6, which is past its EOL.  We need to bring this base image up to a modern python, and then figure out the scripting for CI (do we really need to do everything the Travis setup was doing?).

**Comment by dgrove-oss** [comment]
> @dgrove-oss I create the GitHub action. The configuration in GitHub is still required as I don´t have the necessary permissions.

The secrets the action needs for pushing to dockerhub are already available here.  They were made available to all the OpenWhisk repos when they were created by ASF infrastructure team.

**Comment by Luke-Roy-IBM** [comment]
Hi @dgrove-oss I would start with getting the CI to run again and then look into updating the base image to a supported python version

Thanks for the tips

**Comment by Luke-Roy-IBM** [comment]
@dgrove-oss can you give the code a check please :)

**Comment by dgrove-oss** [comment]
I did try running it (https://github.com/dgrove-oss/openwhisk-runtime-docker/actions/runs/4326403399/jobs/7553773674). Three of the tests are failing.  They appear to be expecting a property file to be built. My guess is that some setup script was supposed to generate that, but I haven't looked into it.


When I've been working on GitHub actions for the other runtimes, I've been testing them on my own fork (knowing that the push to dockerhub will fail), but making sure everything else works.

**Comment by Luke-Roy-IBM** [comment]
@dgrove-oss Github action should be working now and Travis is removed

**Review by dgrove-oss — APPROVED** [review]
LGTM

**Pull request merged**
